# Generated by Django 5.2.4 on 2025-11-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsheader',
            options={'ordering': ['-title']},
        ),
        migrations.RemoveField(
            model_name='newsheader',
            name='link',
        ),
        migrations.RemoveField(
            model_name='newsheader',
            name='publish_date',
        ),
    ]
