# Generated by Django 5.2.4 on 2025-11-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsheader_options_remove_newsheader_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
