# Generated by Django 5.2.4 on 2025-12-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get Out & Play', max_length=200)),
                ('subtitle', models.TextField(default='Explore membership benefits, fees, and all the amenities awaiting you')),
                ('image', models.ImageField(blank=True, null=True, upload_to='membership/')),
            ],
        ),
    ]
