# Generated by Django 5.2.4 on 2025-12-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_amenitiessection_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='icon_svg_path',
        ),
        migrations.AddField(
            model_name='amenity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='aminities/'),
        ),
    ]
