# Generated by Django 5.2.4 on 2025-12-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_remove_amenity_icon_svg_path_amenity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='section',
        ),
    ]
