# Generated by Django 5.2.4 on 2025-12-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_remove_amenity_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='amenities/'),
        ),
    ]
