# Generated by Django 5.2.4 on 2025-12-01 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_golffee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golffee',
            name='fee',
        ),
    ]
