# Generated by Django 5.2.4 on 2025-12-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_remove_golffee_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='golffee',
            name='fee',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
