# Generated by Django 5.2.4 on 2025-11-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(upload_to='videos/thumbnails/')),
                ('position', models.CharField(choices=[('left', 'Left (Main Video)'), ('right', 'Right Side Videos')], max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['position', 'order'],
            },
        ),
    ]
