# Generated by Django 5.2.4 on 2025-11-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_topvideo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopVideo',
            new_name='MostViewdVideos',
        ),
    ]
