# Generated by Django 5.2.4 on 2026-02-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_rename_topvideo_mostviewdvideos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='description',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/logos/'),
        ),
    ]
