# Generated by Django 5.2.4 on 2026-02-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_galleryitem_description_galleryitem_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/logos/'),
        ),
    ]
