# Generated by Django 5.2.4 on 2025-11-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Sponsors', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='sponsors/')),
            ],
            options={
                'verbose_name': 'Sponsor Header',
                'verbose_name_plural': 'Sponsor Header',
            },
        ),
    ]
