# Generated by Django 5.2.4 on 2025-11-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='Together We Grow the Game', max_length=255)),
                ('main_title', models.CharField(default='Building Partnerships', max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners/')),
            ],
            options={
                'verbose_name': 'Partnership Section',
                'verbose_name_plural': 'Partnership Section',
            },
        ),
    ]
