# Generated by Django 5.2.4 on 2025-11-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ghala Golf Club', max_length=255)),
                ('subtitle', models.CharField(default='Since 1971', max_length=255)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
