# Generated by Django 5.2.4 on 2025-11-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/')),
                ('description_1', models.TextField(help_text='First paragraph with highlighted text')),
                ('description_2', models.TextField(help_text='Second paragraph')),
                ('description_3', models.TextField(help_text='Third paragraph')),
                ('button_text', models.CharField(default='View More', max_length=50)),
                ('button_url_name', models.CharField(default='about-us', help_text='URL name for the button link', max_length=50)),
            ],
        ),
    ]
