# Generated by Django 5.2.4 on 2025-11-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, help_text="Upload a team member's photo", null=True, upload_to='team_images/')),
                ('description', models.TextField(blank=True, help_text='Short bio or description for the team member', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of team members on the page')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
    ]
