# Generated by Django 5.2.4 on 2026-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, help_text="Upload a board member's photo", null=True, upload_to='team_images/')),
                ('description', models.TextField(blank=True, help_text='Short bio or description for the board member', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of board members on the page')),
            ],
            options={
                'verbose_name': 'Board Member',
                'verbose_name_plural': 'Board Members',
                'ordering': ['order'],
            },
        ),
    ]
