# Generated by Django 5.2.4 on 2025-11-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
