# Generated by Django 5.2.4 on 2025-12-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLoungeHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Feel the Atmosphere', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('header_image', models.ImageField(upload_to='headers/member_lounge/')),
            ],
        ),
    ]
