# Generated by Django 5.2.4 on 2025-12-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_lounge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoungeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='FontAwesome icon class, e.g. fa-solid fa-utensils', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberLoungeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The Greenview Lounge', max_length=255)),
                ('description_1', models.TextField(blank=True, null=True)),
                ('description_2', models.TextField(blank=True, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='lounge/header/')),
            ],
        ),
    ]
