# Generated by Django 5.2.4 on 2025-12-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_lounge', '0002_loungefeature_memberloungedescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberloungedescription',
            name='header_image',
        ),
    ]
