# Generated by Django 5.2.4 on 2025-12-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_lounge', '0003_remove_memberloungedescription_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLoungeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='member_lounge/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
