# Generated by Django 5.2.4 on 2025-12-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_lounge', '0004_memberloungegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoungeBannerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Relax at Ghala Golf Club Lounge', max_length=255)),
                ('description', models.TextField(default='Experience premium comfort and exceptional amenities at the Ghala Golf Club Lounge, your perfect retreat before a game or event.')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='member_lounge/location_banners/')),
            ],
        ),
        migrations.AlterField(
            model_name='memberloungedescription',
            name='title',
            field=models.CharField(default='Relax by the 18th', max_length=255),
        ),
    ]
