# Generated by Django 5.2.4 on 2025-12-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfAcademyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_image', models.ImageField(upload_to='academy_images/')),
                ('video_file', models.FileField(upload_to='academy_videos/')),
            ],
        ),
    ]
