# Generated by Django 5.2.4 on 2025-12-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_academy', '0002_golfacademycontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfAcademyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image_main', models.ImageField(blank=True, upload_to='golf_academy/', verbose_name='Main Image')),
                ('image', models.ImageField(blank=True, upload_to='golf_academy/', verbose_name='Image')),
            ],
        ),
    ]
