# Generated by Django 5.2.4 on 2025-12-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_academy', '0003_golfacademygallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfacademygallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='golfacademygallery',
            name='title',
        ),
    ]
