# Generated by Django 5.2.4 on 2025-12-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_academy', '0004_remove_golfacademygallery_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfAcademyGalleryDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
